export const cardData = [
    {
      title: "Admin Dashboard",
      description: "Developed a centralized interface allowing users to punch in and out for attendance tracking. Implemented various widgets including Task, Leads, File Manager, Comments, Issue Pending Approvals, Accounts Overview, Finance Overview, and Purchase Order for streamlined management and monitoring of company activities.",
      heading:'Attendance Tracking',
      subHeadin1Content: "Employees can only punch in if a project is present. This requires checking that the user has a project assigned before allowing the punch-in action.",
      subHeadin2Content: "If an employee is out of the location, they must provide a reason for their absence. Implement a form or modal that appears when attempting to punch out, requiring the employee to fill in the reason.",
      subHeadin3Content: "Displays tasks across the company, showing the percentage of progress for each task. This widget helps in tracking task completion and identifying bottlenecks.",
      subHeadin4Content: " Offers detailed insights into the company’s financial health, including income, expenses, and financial performance indicators. For this integrates a Google Line Chart that updates in real-time to display the company's monthly income and loss. This feature provides dynamic financial insights, helping to track performance trends over time.",
      subHeading1:'Punch In Requirements:',
      subHeading2:'Location-Based Punch-Out:',
      subHeading3:'Task Management:',
      subHeading4:'Finance Overview(Google Line Chart):',
    },
    {
      title: "MOM(Minutes of Meeting)",
      description: "As part of my project work, I developed a comprehensive Minutes of Meeting (MOM) feature integrated with React Quill, a powerful rich text editor. This feature facilitates efficient note-taking during meetings, allowing for detailed documentation and enhanced collaboration Key functionalities include:",
      subHeading1:'Rich Text Editing:',
      subHeading2:'Task Creation with Employee Assignment:',
      subHeading3:'Table Insertion and Management:',
      subHeadin1Content: " Leveraged React Quill to provide a robust text editor that supports various formatting options such as bold, italics, underline, bullet points, numbered lists, and more. This ensures that meeting notes are clear, organized, and visually appealing.",
      subHeadin2Content: " Introduced a dynamic task creation system where users can type # to create tasks within the MOM. A dropdown menu appears to select and assign these tasks to specific employees, streamlining task management and follow-up.",
      subHeadin3Content: " Enabled users to insert tables directly within the MOM notes. This feature supports adding and formatting rows and columns, making it easy to structure data and action items effectively.",
     
    },
    {
      title: "Chat",
      description: "I developed an advanced chat feature that mirrors the functionality of WhatsApp but includes unique enhancements tailored for project collaboration.This chat feature enhances project collaboration by integrating essential tools directly into the communication platform, making it easier for teams to share information, track project updates, and stay connected.",
      subHeading1:'File Sharing Integration:',
      subHeading2:'Minutes of Meeting (MOM) Sharing:',  
      subHeading3:'Automatic Room Creation:',
      subHeading4:'Real-Time Messaging:',
      subHeadin1Content: "Users can seamlessly share files from the project's file manager directly within the chat. This integration facilitates easy access to relevant documents and enhances collaborative efforts.",
      subHeadin2Content: "Enabled users to share Minutes of Meeting (MOM) documents directly in the chat, providing quick access to meeting notes and ensuring that all team members are aligned.",
      subHeadin3Content: " When a new project is created, a dedicated chat room is automatically generated with the selected project members, similar to WhatsApp group chats. This ensures immediate and organized communication within each project.",
      subHeadin4Content: "Implemented real-time messaging using sockets, allowing for instant communication between team members. The socket integration was accomplished with assistance from a colleague, ensuring smooth and efficient data transmission",
     
    },
    {
      title: "Timeline & Task Manager",
      description: "I Helped to develop the Timeline and Task Manager modules as essential components of an ERP SaaS product tailored for architecture and interior design firms. These modules are crafted to enhance project management and streamline task coordination, ensuring a seamless workflow and increased productivity.",
      subHeading1:'Project Milestones:',
      subHeading2:'Deadline Tracking:',  
      subHeading3:'Task Creation and Assignment:',
      subHeading4:'Time Tracking and Reporting:',
      subHeadin1Content: " Track key milestones and major project events to ensure timely completion of critical phases.",
      subHeadin2Content: " Monitor deadlines to ensure tasks are completed on time and projects stay on track.",
      subHeadin3Content: " Create and assign tasks to team members, defining roles and responsibilities clearly.Visualize task progress with indicators to monitor completion and identify areas needing attention.",
      subHeadin4Content: " Track the time spent on tasks and generate reports to analyze productivity and project efficiency. Enable team members to collaborate on tasks through comments and discussions.",
     
    },
    {
      title: "Material Request Dashboard",
      description: "I developed the Timeline and Task Manager modules as essential components of an ERP SaaS product tailored for architecture and interior design firms. These modules are crafted to enhance project management and streamline task coordination, ensuring a seamless workflow and increased productivity.",
      subHeading1:'Material Request:',
      subHeading2:'Bulk Ordering:',  
      subHeading3:'Order History:',
      subHeading4:'User-Friendly Interface:',
      subHeadin1Content: "Allows employees to submit requests for various materials needed for interior projects. This includes a range of items such as paints, sofas, fans, marble, and more.",
      subHeadin2Content: "Facilitates ordering multiple items simultaneously, simplifying the procurement process and ensuring that all required materials are purchased in one go.",
      subHeadin3Content: "Records and maintains a history of all orders placed through the dashboard. This feature provides easy access to past order details, enabling better tracking and management of material requests.",
      subHeadin4Content: "Offers an intuitive interface that simplifies the process of requesting and ordering materials, making it easy for employees to manage their material needs efficiently.",
     
    },
    {
      title: "Project Dashboard",
      description: "I developed a comprehensive Project Information feature that centralizes critical project details into a single, user-friendly interface. This feature is designed to enhance project management, streamline communication, and ensure that all relevant information is readily accessible.",
      subHeading1:'Comments Section:',
      subHeading2:'Pending Approvals:',  
      subHeading3:'Project Members(One-To-One Chat):',
      subHeading4:'Real-Time Updates:',
      subHeadin1Content: " Allows team members to post and view comments related to the project. This feature promotes collaboration and ensures that feedback and discussions are easily accessible.",
      subHeadin2Content: "Displays a list of all pending approvals required for the project. This helps in managing workflows and ensuring that necessary approvals are obtained promptly to avoid delays.",
      subHeadin3Content: " Shows a roster of all project members, including their roles, contact details, and responsibilities. This feature helps in identifying key contacts and understanding team composition. Features a direct messaging system that allows project members to communicate one-on-one",
      subHeadin4Content: "Ensures that all information, including comments, approvals, issues, and tasks, is updated in real-time. This feature keeps all team members informed of the latest developments and changes.",
     
    },
    // Add more card data objects as needed
  ];